eo_gestion/urls.py
# barbacompta - invoicing for dummies
# Copyright (C) 2019-2020 Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import django.contrib.admin
from django.conf import settings
from django.urls import include, path, re_path

from . import admin
from .eo_facture.views import api_references

django.contrib.admin.autodiscover()

urlpatterns = [
    path('api/references/', api_references),
    re_path(r'^', admin.site.urls),
]

if 'mellon' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('accounts/mellon/', include('mellon.urls')),
    ] + urlpatterns

eo_gestion/eo_facture/models.py
# barbacompta - invoicing for dummies
# Copyright (C) 2019-2020 Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import dataclasses
import datetime
import hashlib
import os.path
import urllib.parse
from collections import defaultdict
from decimal import ROUND_HALF_UP, Decimal

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.staticfiles import finders
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, validate_email
from django.db import models, transaction
from django.db.models import F, Q, Sum
from django.db.models.query import QuerySet
from django.db.models.signals import post_delete, post_save
from django.template.loader import get_template
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from weasyprint import HTML, default_url_fetcher

from eo_gestion.utils import percentage_str

from ..eo_banque import models as banque_models
from . import facturx, fields, taggit, validators

User = get_user_model()

validate_telephone = RegexValidator(r'[. 0-9]*')

DEFAULT_TVA = getattr(settings, 'TVA', '20')


def accounting_rounding(amount):
    return amount.quantize(Decimal('0.01'), ROUND_HALF_UP)


def today():
    return now().date()


def my_url_fetcher(url):
    parsed = urllib.parse.urlparse(url)
    if (path := parsed.path).startswith('/static/'):
        result = finders.find(path.split('/static/', 1)[1])
        ext = path.rsplit('.', 1)[1]
        # the facture.html template refers only to .css and .png files, add
        # more mime-types if other types are used in the future
        mime_types = {
            'css': 'text/css',
            'png': 'image/png',
        }
        return {'file_obj': open(result, 'rb'), 'mime_type': mime_types.get(ext, 'application/octet-stream')}
    return default_url_fetcher(url)


class Client(models.Model):
    nom = models.CharField(max_length=255, unique=True)
    notes_privees = models.TextField(verbose_name='Notes privées', blank=True)
    adresse = models.TextField()
    email = models.CharField(max_length=50, validators=[validate_email], verbose_name='Courriel', blank=True)
    telephone = models.CharField(
        max_length=20, validators=[validate_telephone], verbose_name='Téléphone', blank=True
    )
    contacts = models.TextField(verbose_name=_('Contacts'), blank=True)
    monnaie = models.CharField(max_length=10, default='€')
    tva = models.DecimalField(
        verbose_name='TVA par défaut', max_digits=4, decimal_places=2, default=Decimal(DEFAULT_TVA)
    )
    picture = models.ImageField('Logo', upload_to='logos/', blank=True, null=True)
    siret = models.CharField(
        max_length=len('29202001300010'),
        validators=[validators.validate_siret],
        db_index=True,
        blank=True,
        default='',
    )
    service_code = models.CharField(
        max_length=128,
        db_index=True,
        blank=True,
        default='',
    )
    active = models.BooleanField(verbose_name='Actif', default=True)

    chorus_structure = models.ForeignKey(
        'chorus.Structure',
        verbose_name='Structure ChorusPro',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):  # pylint: disable=invalid-str-returned
        return self.nom

    def clean(self):
        self.service_code = self.service_code.strip()
        if self.chorus_structure:
            self.siret = self.chorus_structure.siret
            self.service_code = self.chorus_structure.service_code

    @classmethod
    @transaction.atomic
    def update_siret_and_service_code(cls):
        clients_to_update = (
            Client.objects.filter(Q(chorus_structure__isnull=False))
            .exclude(siret=F('chorus_structure__siret'), service_code=F('chorus_structure__service_code'))
            .annotate(
                new_siret=F('chorus_structure__siret'), new_service_code=F('chorus_structure__service_code')
            )
        )

        for client in clients_to_update:
            client.siret = client.new_siret
            client.service_code = client.new_service_code
            client.save(update_fields=['siret', 'service_code'])

    class Meta:
        ordering = ('nom',)


def one_hundred_percent_this_year():
    return '%s:100' % now().date().year


class Contrat(models.Model):
    client = models.ForeignKey(
        Client, related_name='contrats', on_delete=models.CASCADE, blank=False, null=True
    )
    intitule = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    public_description = models.TextField(
        verbose_name='Description publique',
        blank=True,
        help_text='Si elle est présente, cette description sera reprise dans la liste des références sur le site web.',
    )
    url = models.URLField(verbose_name=_('URL'), blank=True)
    tva = models.DecimalField(
        max_digits=4, decimal_places=2, default=Decimal(DEFAULT_TVA), blank=True, null=True
    )
    creation = models.DateField(default=today)
    creator = models.ForeignKey(User, verbose_name='Créateur', on_delete=models.CASCADE)
    percentage_per_year = fields.PercentagePerYearField(
        default=one_hundred_percent_this_year,
        verbose_name='Pourcentage par année',
        help_text='Incompatible avec la périodicité',
    )
    montant_sous_traite = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('0'))
    image = models.ImageField('Image', upload_to='images/', blank=True, null=True)
    numero_marche = models.CharField(max_length=128, verbose_name='Numéro du marché', blank=True, default='')

    periodicite = models.CharField(
        verbose_name='Périodicité',
        max_length=16,
        choices=[
            ('annuelle', 'Annuelle'),
            ('semestrielle', 'Semestrielle'),
        ],
        blank=True,
        null=True,
    )
    periodicite_debut = models.DateField(verbose_name='Périodicité début', blank=True, null=True)
    periodicite_fin = models.DateField(verbose_name='Périodicité fin', blank=True, null=True)
    periodicite_a_terme_echu = models.BooleanField(
        verbose_name='Facturé à terme échu', blank=True, default=False
    )

    tags = taggit.TaggableManager(blank=True)

    def montant_facture(self):
        return sum(facture.montant for facture in self.factures.non_proforma())

    def pourcentage_facture(self):
        return percentage_str(self.montant_facture(), self.montant())

    pourcentage_facture.short_description = 'Pourcentage facturé'

    @property
    def montant_prestations(self):
        return Decimal(sum(p.montant() for p in self.prestations.all()))

    def montant(self):
        """
        Montant total d'un contrat, y compris les prestations
        optionnelles. Si pas de prestation définie, montant des factures émises.
        """
        if self.prestations.exists():
            montant = self.montant_prestations
            if self.periodicite and self.periodicite_debut:
                return montant * self.periodicite_nombre_d_echeances()
            else:
                return montant

        else:
            return self.montant_facture()

    def solde(self):
        return self.montant() - self.montant_facture()

    def montant_par_annee(self):
        '''
        Calcul du revenu futur, en retranchant les
        montants déjà facturés par rapport au
        prévisionnel
        '''

        today_year = datetime.date.today().year
        montant_par_annee = defaultdict(Decimal)
        adjust = 0
        if not self.periodicite:
            for year, fraction in self.percentage_per_year:  # pylint: disable=not-an-iterable
                amount = self.montant() * fraction
                if year > today_year:
                    montant_par_annee[year] += amount
                else:
                    adjust += amount
        else:
            # calcule le montant par periode en sommant le montant des
            # prestations puis impute à chaque année ce même montant pour
            # chaque échéance arrivant dans cette année, pour les montants de
            # l'année en cours et des précédentes, tout mettre dans l'année
            # courante, ce sera diminué du total des factures déjà faites (même
            # comportement que dans le cas classique)
            montant = self.montant_prestations
            for echeance in self.periodicite_echeances(limit=20):
                if echeance.facturation.year > today_year:
                    montant_par_annee[echeance.facturation.year] += montant
                else:
                    adjust += montant
        for f in self.factures.all():
            if f.proforma:
                continue
            if f.accounting_year <= today_year:
                adjust -= f.montant - f.sous_traite
        if adjust > 0:
            montant_par_annee[today_year] += adjust
        return montant_par_annee

    def clean(self):
        self.numero_marche = self.numero_marche.strip()

        if self.periodicite and not self.periodicite_debut:
            raise ValidationError(
                {'periodicite_debut': 'Vous devez définir une date de début pour la période.'}
            )
        if self.periodicite_debut and not self.periodicite:

eo_gestion/eo_facture/views.py
# barbacompta - invoicing for dummies
# Copyright (C) 2010-2020 Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import logging

from django import http
from django.contrib import messages
from django.contrib.admin.models import LogEntry
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404, redirect

from eo_gestion.chorus.utils import push_to_chorus

from .models import Contrat, Facture

logger = logging.getLogger(__name__)


def facture(request, facture):
    return http.Response(
        get_object_or_404(Facture, id=facture).html(base_uri=request.build_absolute_uri('/'))
    )


def facture_pdf(request, facture_id):
    facture = get_object_or_404(Facture, id=facture_id)
    if 'facturx' in request.GET:
        pdf = facture.facturx_pdf(base_uri=request.build_absolute_uri('/'))
    else:
        pdf = facture.pdf(base_uri=request.build_absolute_uri('/'))
    return http.HttpResponse(pdf, content_type='application/pdf')


def api_references(request):
    data = []
    qs = (
        Contrat.objects.exclude(public_description='')
        .exclude(client__picture__isnull=True)
        .exclude(client__picture='')
        .prefetch_related('tags')
    )
    if 'tags' in request.GET:
        qs = qs.filter(tags__name__in=request.GET.getlist('tags'))
    for contract in qs:
        data.append(
            {
                'title': contract.intitule,
                'description': contract.public_description,
                'client': contract.client.nom,
                'logo': request.build_absolute_uri(contract.client.picture.url),
                'url': contract.url,
                'tags': [tag.name for tag in contract.tags.all()],
            }
        )
        if contract.image:
            data[-1]['image'] = request.build_absolute_uri(contract.image.url)
    return http.JsonResponse({'data': data})


def send_to_chorus(request, facture_id):
    facture = get_object_or_404(Facture, id=facture_id)

    if facture.client.chorus_structure and not facture.proforma:
        logger.info('sending invoice %s to ChorusPro', facture)
        response = push_to_chorus(
            facture.facturx_pdf(base_uri=request.build_absolute_uri('/')), facture.code() + '.pdf'
        )

        description = ''
        if 'numeroFluxDepot' in response:
            msg = f'Facture {facture.code()} envoyée à ChorusPro'
            for key, value in response.items():
                description += f' | {key} - {value}'
        else:
            msg = f'Échec d\'envoi de la facture {facture.code()} à ChorusPro'

        msg += description
        LogEntry.objects.create(
            user=request.user,
            content_type=ContentType.objects.get_for_model(facture),
            object_id=facture_id,
            object_repr=str(facture),
            action_flag=0,
            change_message=msg,
        )

        if 'numeroFluxDepot' in response:
            logger.info('sent invoice %s to ChorusPro, response: %s', facture, description)
            messages.info(request, msg)
        else:
            logger.warning('failed to send invoice %s to ChorusPro, response: %s', facture, description)
            messages.error(request, msg)
    return redirect('admin:eo_facture_facture_change', facture_id)


def cancel(request, facture_id):
    facture = get_object_or_404(Facture, id=facture_id)
    facture_avoir = facture.cancel(request.user)
    return redirect('admin:eo_facture_facture_change', facture_avoir.id)

eo_gestion/eo_facture/templates/eo_facture/a_facturer.html
{% load eo_facture %}
{% if a_facturer %}
  <div class="module" id="a-facturer">
    <h2>Reste à facturer</h2>
    <p>Liste des contrats qu'on a pas facturés depuis un bon moment et pour lesquels il reste un solde à facturer.</p>
    <p>Montant total: {{ montant|amountformat }} € HT</p>
    <table class="table">
      <thead>
        <th class="contrat">Contrat</th>
        <th class="pourcentage">Pourcentage facturé</th>
        <th class="montant">Reste HT</th>
        <th class="derniere-facture">Depuis</th>
      </thead>
      <tbody>
        {% for l in a_facturer %}
          <tr>
            <td class="contrat">
              <a href="{% url "admin:eo_facture_contrat_change" l.contrat.id %}">
                {{ l.contrat.intitule }}
                <a/>
              </td>
              <td class="pourcentage">{{ l.pourcentage|floatformat:2 }} %</td>
              <td class="montant">{{ l.montant|amountformat }} €</td>
              <td class="derniere-facture">{{ l.depuis }} jours</td>
            </tr>
        {% endfor %}
      </table>
    </div>
{% endif %}

eo_gestion/eo_facture/templates/eo_facture/echeances.html
{% load eo_facture %}
{% if echeances %}
  <div class="module" id="echeances">
    <h2>Contrats récurrents à facturer</h2>

    <table id="echeance" class="table">
      <colgroup>
        <col class="debut"/>
        <col class="client"/>
        <col class="contrat"/>
        <col class="numero"/>
        <col class="periodicite"/>
      </colgroup>
      <thead>
        <th class="debut">Date de facturation</th>
        <th class="periode">Période</th>
        <th class="client">Client</th>
        <th class="contrat">Contrat</th>
        <th class="numero">Numéro d'échéance</th>
        <th class="periodicite">Périodicité</th>
        <th class="facturer"></th>
      </thead>
      <tbody>
        {% for echeance in echeances %}
          <tr>
            <td class="facturation">{{ echeance.facturation|date:"d/m/Y" }}</td>
            <td class="periode">{{ echeance.debut|date:"d/m/Y" }} - {{ echeance.fin|date:"d/m/Y" }}</td>
            <td class="client"><a href="{% url "admin:eo_facture_client_change" echeance.contrat.client.id %}">{{ echeance.contrat.client }}</a></td>
            <td class="contrat">
              <a href="{% url "admin:eo_facture_contrat_change" echeance.contrat.id %}">
                {{ echeance.contrat.intitule }}
              </a>
            </td>
            <td class="numero">{{ echeance.numero }} / {{ echeance.contrat.periodicite_nombre_d_echeances }}</td>
            <td class="periodicite">{{ echeance.contrat.get_periodicite_display }}</td>
            <td class="facturer">
              <form method="post" action="{% url "admin:eo_facture_contrat_facturer_echeance" echeance.contrat.id %}">
                {% csrf_token %}
                <input type="hidden" name="echeance" value="{{ echeance.numero }}"/>
                <input type="submit" value="Facturer" style="padding: 2px 3px"/>
              </form>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
{% endif %}

eo_gestion/eo_facture/templates/eo_facture/impayee.html
{% load eo_facture %}
{% if factures %}
  <div class="module" id="impayees">
    <h2>Impayées</h2>
    <p>Montant total: {{ montant|amountformat }} € TTC ({{montant_ht|amountformat}} € HT) </p>
    <table id="impayee">
      <thead>
        <th>Quoi?</th>
        <th>Depuis...</th>
      </thead>
      <tbody>
        {% for l in factures %}
          {% with l.facture as facture %}
            <tr class="facture{% if l.encaissements %} encaissement{% endif %}{% if l.vieille %} vieille{% endif %}"><td>
              <div class="facture"><a href="{% url "admin:eo_facture_facture_change" facture.pk_or_code %}">{{ facture.code }} - {{facture.intitule}}<a/> pour {{ facture.solde|amountformat }} {{ facture.contrat.client.monnaie }} TTC à <a href="{% url "admin:eo_facture_client_change" facture.client.id %}">{{facture.client}}</a></div>
              </td>
              <td>{{facture.emission|ago}}</td>
            </tr>
              {% if l.encaissements %}
                {% for encaissement in l.encaissements %}
                  <tr class="encaissements">
                    <td border="0">
                      <a href="{% url "admin:eo_banque_lignebanquepop_change" encaissement.id%}">{{ encaissement.libelle }} - {{ encaissement.reference }} - payé le {{ encaissement.date_valeur }}</a> de {{ encaissement.montant|amountformat }} €</td>
                    <td>
                      <a href="{% url "admin:eo_facture_payment_add" %}?facture={{ facture.id }}&ligne_banque_pop={{ encaissement.id }}&montant_affecte={{ encaissement.montant|stringformat:".2f" }}">Accepter</a>
                    </td>
                  </tr>
                {% endfor %}
              {% endif %}
          {% endwith %}
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endif %}

eo_gestion/eo_facture/templates/eo_facture/income.html
{% load eo_facture %}
<div class="module" id="income">
  <table id="income-table" class="table">
    <caption>Chiffre d'affaire par an</caption>
    <thead>
      <tr>
        <th>Année</th>
        {% for i in income_by_year %}
          <th>{{ i.year }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Encaissé</td>
        {% for i in income_by_year %}
          <td>{{ i.paid|amountformat }}</td>
        {% endfor %}
      </tr>
      <tr>
        <td>Facturé</td>
        {% for i in income_by_year %}
          <td>{{ i.invoiced|amountformat }}</td>
        {% endfor %}
      </tr>
      <tr>
        <td>Contracté</td>
        {% for i in income_by_year %}
          <td>{{ i.contracted|amountformat }}</td>
        {% endfor %}
      </tr>
      <tr>
        <td>Sous-traité</td>
        {% for i in income_by_year %}
          <td>{{ i.sous_traite|amountformat }}</td>
        {% endfor %}
      </tr>
      <tr>
        <td>Total</td>
        {% for i in income_by_year %}
          <td>{{ i.total|amountformat }}</td>
        {% endfor %}
      </tr>
    </tbody>
  </table>
</div>

eo_gestion/eo_facture/templates/eo_facture/table.html
{% load eo_facture %}
<div class="module" id="module-table-{{name}}">
  <table id="table-{{name}}" class="table">
    <caption>{{title}}</caption>
    <!-- headers -->
    <thead>
      {% for header, header_title in headers %}
        <th class="header-{{header}}">{{header_title}}</th>
      {% endfor %}
    </thead>
    <tbody>
      {% for row in table %}
        <tr>
          {% if row.0.href %}
            <td><a href="{{ row.0.href }}">{{ row.0 }}</a></td>
          {% else %}
            <td>{{ row.0 }}</td>
          {% endif %}
          <td class="number-cell">{{ row.1|amountformat }}</td>
          <td class="number-cell">{{ row.2|amountformat }}</td>
          <td class="number-cell">{{ row.3|floatformat:2 }} %</td>
          <td class="number-cell">{{ row.4|amountformat }}</td>
          <td class="number-cell">{{ row.5|floatformat:2 }} %</td>
          <td class="number-cell">{{ row.6|floatformat:2 }} %</td>
          <td class="number-cell">{{ row.7|floatformat:2 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
</div>